app:
  http_port: 8080  
  grpc_port: 3000 
  env: development
  idle_timeout: 1m
  read_timeout: 30s
  write_timeout: 60s
  shutdown_timeout: 10s
  jwt_token_ttl: 24h

postgres:                     
  max_pool_size: 50
  conn_timeout: 10s
  driver: pgx